server {
    listen 80;
    listen [::]:80;
    server_name __DOMAIN__;

    root __WEBROOT__;
    index index.html;

    location /.well-known/acme-challenge/ {
        root __WEBROOT__;
        default_type "text/plain";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
